### ISSUE TITLE
Update text comment on BQSKit notebook

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/research#12]
Hi @natestemen, I guess this comment should be removed since we don't use a volume circuit anymore:

https://github.com/unitaryfund/research/blob/d1e4448e9cf572455fddcf4fa6416406645c441f/ieee-quantum-week/compilation-with-error-mitigation-tutorial/bqskit.ipynb?short_path=5531e7e#L290

**Comment by natestemen** [comment]
Ah good catch. I'll get that patched up here asap.

**Comment by nathanshammah** [comment]
I was also wondering if in the next version, we could explain briefly that the quantum volume function is used just as a useful ready-to-use way to have random circuits, but we do not really use it to do a quantum volume test. This could be not immediately clear to a user.

**Comment by natestemen** [comment]
In the latest version we don't use quantum volume circuits. Do you still think it's worth mentioning?
